guard 'compass' do
  watch %r{sass/.+(\.s[ac]ss)}
end

guard 'coffeescript', :output => 'js/compiled' do
  watch(%r{coffeescripts/(.+\.coffee)})
end

guard 'livereload' do
  watch(%r{js/.+\.js})
  watch(%r{js/compiled/.+\.js})
  watch(%r{../View/.+/.+\.ctp})
  watch(%r{css/.+\.css})
end
